Création des tricks et de l'espace d'affichage
nbahire/Projet6_snow pull request #10
Opened 2023-01-26 13:30 UTC by nbahire

2023-02-17 10:41 UTC, TBoileau requested changes

2023-02-17 10:41 UTC, TBoileau commented on composer.json
> +        "liip/imagine-bundle": "^2.10",
A supprimer

2023-02-17 10:41 UTC, TBoileau commented on composer.json
>          "symfonycasts/verify-email-bundle": "^1.13",
A supprimer

2023-02-17 10:41 UTC, TBoileau commented on composer.json
> +        "vich/uploader-bundle": "^2.0"
A supprimer

2023-02-17 10:41 UTC, TBoileau commented on config/bundles.php
> +    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
A supprimer

2023-02-17 10:41 UTC, TBoileau commented on src/Controller/MainController.php
> +        $request->getSession()->set('referer', $request->getUri());
Quel est l'intérêt de stocker l'url dans la session ?

2023-02-17 10:41 UTC, TBoileau commented on src/Controller/MainController.php
> +            $trick->addComment($comment);
Cette ligne la est inutile.

2023-02-17 10:41 UTC, TBoileau commented on src/Entity/User.php
> +    }
Ce code la est inutile car la persistance des commentaires se gère de manière individuel pour les commentaires, on ne passe pas par Trick pour persister Comment

2023-02-17 10:41 UTC, TBoileau commented on src/Entity/Comment.php
> +    private ?\DateTimeImmutable $created_at = null;
Attention a bien respecter le PSR1 et donc respecter le camelCase (bien vérifier dans les autres classes, notamment Trick ou il y a aussi la même erreur)

2023-02-17 10:41 UTC, TBoileau commented on src/Entity/Trick.php
> +    private ?\DateTimeImmutable $updated_at = null;
Respecter le PSR1 et donc faire du camelCase

2023-02-17 10:41 UTC, TBoileau commented on templates/main/show.html.twig
> +                            <a href="#" onclick="event.preventDefault(); confirm('Etes-vous sur ?')&& document.getElementById('trick-delete').submit();" class=" btn btn-light ">Supprimer</a>
Eviter le inline JS.

2023-02-17 10:41 UTC, TBoileau commented on src/Controller/User/UserController.php
> +}
A supprimer

2023-02-17 10:41 UTC, TBoileau commented on src/Controller/User/TrickCrudController.php
> +}
A supprimer

2023-02-19 21:16 UTC, nbahire commented on src/Controller/User/TrickCrudController.php
> +}
done

2023-02-19 21:16 UTC, nbahire commented on src/Controller/User/UserController.php
> +}
done

2023-02-19 21:17 UTC, nbahire commented on src/Entity/Trick.php
> +    private ?\DateTimeImmutable $updated_at = null;
done

2023-02-19 21:17 UTC, nbahire commented on src/Entity/Comment.php
> +    private ?\DateTimeImmutable $created_at = null;
done

2023-02-19 21:17 UTC, nbahire commented on src/Controller/MainController.php
> +        $request->getSession()->set('referer', $request->getUri());
done

2023-02-19 21:17 UTC, nbahire commented on config/bundles.php
> +    Liip\ImagineBundle\LiipImagineBundle::class => ['all' => true],
done

2023-02-19 21:17 UTC, nbahire commented on composer.json
> +        "vich/uploader-bundle": "^2.0"
done

2023-02-19 21:17 UTC, nbahire commented on composer.json
>          "symfonycasts/verify-email-bundle": "^1.13",
done

2023-02-19 21:17 UTC, nbahire commented on composer.json
> +        "liip/imagine-bundle": "^2.10",
done

2023-02-19 21:17 UTC, merged